import { newsletter, initNewsletter } from '../JS/components/newsletter.js';

const contactDetails = [['Visit us', '18, Park Street\nBengaluru, KA 560001'], ['Call us', '+91 80 4112 0198\nMon–Fri, 9am–6pm'], ['Write to us', 'hello@swooshstore.in\nWe reply within one business day'], ['Business hours', 'Monday–Friday: 9am–6pm\nSaturday: 10am–4pm']];
const faqs = [['When will my order arrive?', 'Most orders arrive within 3–5 business days. You will receive tracking details as soon as your order leaves our studio.'], ['How do I start a return?', 'Start from your order confirmation or contact our support team. Returns are free within 30 days for unworn items.'], ['Can I change my order?', 'We begin preparing orders quickly, but our support team will always check what is possible before dispatch.'], ['Which payment methods do you accept?', 'We accept major cards, UPI, and supported digital wallets through our secure checkout.']];

export function render() {
  return `<section class="contact-page" data-page="contact"><header class="contact-hero"><div class="section-shell"><p class="eyebrow">Get in touch <span></span></p><h1>Let’s make<br><em>moves together.</em></h1><p>Whether you need help with an order or simply want to say hello, our team is here.</p></div></header><section class="contact-main section-shell"><div class="contact-details">${contactDetails.map(([title, text]) => `<article><span aria-hidden="true">＋</span><h2>${title}</h2><p>${text.replace('\n', '<br>')}</p></article>`).join('')}</div><section class="contact-form-panel" aria-labelledby="contact-form-title"><div><p class="eyebrow eyebrow--dark">Send a message</p><h2 id="contact-form-title">How can we help?</h2><p>Tell us a little about what you need and we’ll get back to you shortly.</p></div><form data-contact-form novalidate><label>Name<input name="name" autocomplete="name" required aria-describedby="name-error"></label><small id="name-error" data-error-for="name"></small><label>Email<input name="email" type="email" autocomplete="email" required aria-describedby="email-error"></label><small id="email-error" data-error-for="email"></small><label>Subject<input name="subject" required aria-describedby="subject-error"></label><small id="subject-error" data-error-for="subject"></small><label>Message<textarea name="message" rows="5" required aria-describedby="message-error"></textarea></label><small id="message-error" data-error-for="message"></small><button class="contact-submit" type="submit">Send message <span aria-hidden="true">→</span></button><p class="contact-form__status" data-contact-status aria-live="polite"></p></form></section></section><section class="contact-map section-shell"><div class="contact-map__visual" role="img" aria-label="Map placeholder showing the Bengaluru studio"><span></span><i>Our Bengaluru studio</i></div><div><p class="eyebrow eyebrow--dark">Find us</p><h2>Come say<br>hello.</h2><p>Map integration is coming soon. Until then, use the address above to plan your visit.</p></div></section><section class="contact-faq section-shell"><div><p class="eyebrow eyebrow--dark">Helpful answers</p><h2>Frequently asked.</h2></div><div>${faqs.map(([question, answer], index) => `<details ${index === 0 ? 'open' : ''}><summary>${question}<span aria-hidden="true">+</span></summary><p>${answer}</p></details>`).join('')}</div></section>${newsletter()}</section>`;
}

export function init() {
  initNewsletter();
  const form = document.querySelector('[data-contact-form]');
  form?.addEventListener('submit', (event) => {
    event.preventDefault(); let valid = true;
    [...form.elements].filter((field) => field.name).forEach((field) => { const error = form.querySelector(`[data-error-for="${field.name}"]`); const message = field.validity.valueMissing ? `Please enter your ${field.name}.` : field.validity.typeMismatch ? 'Enter a valid email address.' : ''; error.textContent = message; field.setAttribute('aria-invalid', Boolean(message)); if (message) valid = false; });
    const status = form.querySelector('[data-contact-status]');
    if (!valid) { status.textContent = 'Please review the highlighted fields.'; form.querySelector('[aria-invalid="true"]')?.focus(); return; }
    form.reset(); form.querySelectorAll('[aria-invalid]').forEach((field) => field.removeAttribute('aria-invalid')); status.textContent = 'Thanks — your message has been sent. We’ll be in touch soon.';
  });
}
